server:
  port: 8090

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: https://api.openai.com/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: 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

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_cb0f05c7f3f5
    appid: wx4f04e45b5e870e62
    token: b8b6

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml